<a href="https://colab.research.google.com/github/cadumack/Paradigmas/blob/main/C%C3%B3pia_de_Trilha4_Final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

WHO = pd.read_csv('https://raw.githubusercontent.com/Rogerio-mack/Visualizacao-de-Dados-em-Python/main/data/Life_Expectancy_Data.csv')
WHO.rename(columns={' BMI ':'BMI', 'Life expectancy ':'Life_expectancy'}, inplace=True)
WHO = WHO[ WHO.Year == 2015]

WHO.head()

# WHO.loc[WHO.Polio(5).index]

# PosiÃ§Ã£o do Brasil no ranking Schooling
# WHO.loc[WHO.Schooling.nlargest(39).index]


# verificar e analisar a expectativa de vida
# WHO.loc[WHO.Life_expectancy.nlargest(12).index][['Status','Country', 'Year']]
# WHO.loc[WHO.GDP.nsmallest(5).index]

# ComparaÃ§Ã£o entre pasies Desenvolvido e Subdesenvolvidos
# plt.figure(figsize=(14,4))
# sns.countplot(x=WHO.Status)
# plt.title('Desenvolvidos x Subdesenvolvidos')
# plt.xticks(rotation=45)
# plt.show()

# Dislpay( WHO.status.value_counts()[0:10] )

# display(WHO.shape)
# display(WHO.head())

# display(WHO.GDP.min(),WHO.GDP.max())

# VerificaÃ§Ã£o de valores nulos
# print(WHO.isnull().sum())
# print(WHO.describe())

,Country,Year,Status,Life_expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,...,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
16,Albania,2015,Developing,77.8,74.0,0,4.60,364.975229,99.0,0,...,99.0,6.00,99.0,0.1,3954.227830,28873.0,1.2,1.3,0.762,14.2
32,Algeria,2015,Developing,75.6,19.0,21,NaN,0.000000,95.0,63,...,95.0,NaN,95.0,0.1,4132.762920,39871528.0,6.0,5.8,0.743,14.4
48,Angola,2015,Developing,52.4,335.0,66,NaN,0.000000,64.0,118,...,7.0,NaN,64.0,1.9,3695.793748,2785935.0,8.3,8.2,0.531,11.4
64,Antigua and Barbuda,2015,Developing,76.4,13.0,0,NaN,0.000000,99.0,0,...,86.0,NaN,99.0,0.2,13566.954100,NaN,3.3,3.3,0.784,13.9